### ISSUE TITLE
Non-root routes returns 404 error

### ISSUE THREAD

**Issue by vivanov1410** [makkke/road-so-far-app#6]
### Steps to reproduce:
1. go to https://app.roadsofar.com/login

### Actual result:
S3 404 error is shown

### Expected result:
Login page should be open. Looks like its a server side routing problem because everything is working after going to root url.

**Comment by nenadknezevic** [comment]
http://aserafin.pl/2016/03/23/react-router-on-amazon-s3/

Created custom error response on CloudFront for 404 error. Set response path to /index.html and status to 200.
