### ISSUE TITLE
AWS cloudfront not updating on update of files in S3

### ISSUE THREAD

**Issue by vivanov1410** [makkke/road-so-far-app#8]
**Steps to reproduce:**
- update files on S3 (new app version for example)
- access app via Cloudfront (app.roadsofar.com)

**Actual result:**
Still shows old files.

**Expected result:**
Should show updated files.

**Notes**:
Probably something to do with caching. See http://stackoverflow.com/questions/30154461/aws-cloudfront-not-updating-on-update-of-files-in-s3

**Comment by nenadknezevic** [comment]
Had to disable caching by going to:

1. CloudFront distributions
2. Behaviour tab
3. Edit behaviour
4. Object caching set to "customize"
5. Set all 3 TTL values to 0

The updates are immediate and we no longer need to clear the browser cache either.

Though I'm wondering if bypassing the cache like this and going to the origin for everything has any cost implications? Can you check your billing or however you are doing it to see if you are being charged for frequent access to the origin?
